name: QT AWS Assume Role
description: Assumes AWS IAM role and exports credentials to ENV
author: qrious
inputs:
  region:
    description: AWS region name
    default: null
    required: false
  duration-seconds:
    description: The duration, in seconds, of the role session
    default: 3600
    required: false
  role-arn:
    description: The Amazon Resource Name (ARN) of the role to assume
    required: true
  role-session-name:
    description: An identifier for the assumed role session
    default: GitHub-Action
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: users
  color: orange
